# Generated by Django 3.1.2 on 2020-10-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='uf',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
