# Generated by Django 3.1.2 on 2020-11-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201114_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='alimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='dinheiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='roupa',
            field=models.BooleanField(default=False),
        ),
    ]
