# Generated by Django 3.1.2 on 2020-11-15 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201114_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.usuario'),
        ),
    ]
