# Generated by Django 3.1.2 on 2020-11-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_doacao_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doacao',
            new_name='Publicacao',
        ),
    ]
